language: cpp

sudo: false

env:
  matrix:
    - COMPILER=g++-4.9
    - COMPILER=g++-5
    - COMPILER=clang++-3.6
    - COMPILER=clang++-3.7

matrix:
  include:
    - os: linux
    - os: osx
      osx_image: xcode6.4
    - os: osx
      osx_image: xcode7

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-precise
      - llvm-toolchain-precise-3.6
      - llvm-toolchain-precise-3.7
    packages:
      - g++-4.9
      - g++-5
      - clang-3.6
      - clang-3.7

before_script:
  - export CXX=$COMPILER

script:
  - make
