version: 1.0.{build}
os:
  - Visual Studio 2015

platform:
  - Win32
  - x64

environment:
  matrix:
    - PlatformToolset: v120
    - PlatformToolset: v140

before_build:
  - cmd: set

build_script:
  - msbuild /p:PlatformToolset="%PlatformToolset%" "test.vcxproj"  /logger:"%ProgramFiles%\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"

configuration:
  - Debug
  - Release
