version: 1.0.{build}
os:
  - Visual Studio 2013
  - Visual Studio 2015

build:
  project: test.vcxproj

platform:
    - Win32
    - x64

environment:
  matrix:
    - PlatformToolset: v120
      os: Visual Studio 2013
    - PlatformToolset: v140
      os: Visual Studio 2015

configuration:
  - Debug
  - Release
